
   lazy.nvim (H)   Install (I)   Update (U)   Sync (S)   Clean (X)   Check (C)   Log (L)   Restore (R)   Profile (P)   Debug (D)   Help (?) 

  Startuptime: 63.16ms

  Based on the actual CPU time of the Neovim process till UIEnter.
  This is more accurate than `nvim --startuptime`.
    LazyStart 17.1ms
    LazyDone  60.72ms (+43.62ms)
    UIEnter   63.16ms (+2.44ms)

  Profile

  You can press <C-s> to change sorting between chronological order & time taken.
  Press <C-f> to filter profiling entries that took more time than a given threshold

    ●  lazy.nvim 43.94ms
      ➜  module 4.32ms
      ➜  config 0.55ms
      ➜  spec 26.79ms
        ★  pkg 0.42ms
        ★  lazyvim.plugins 3.76ms
        ★  lazyvim.plugins.coding 0.24ms
        ★  lazyvim.plugins.colorscheme 0.19ms
        ★  lazyvim.plugins.editor 1ms
          ‒  lazyvim.plugins.extras.editor.fzf 0.23ms
        ★  lazyvim.plugins.formatting 0.35ms
        ★  lazyvim.plugins.linting 0.24ms
        ★  lazyvim.plugins.lsp 0.6ms
        ★  lazyvim.plugins.treesitter 0.16ms
        ★  lazyvim.plugins.ui 0.52ms
        ★  lazyvim.plugins.util 0.3ms
        ★  lazyvim.plugins.xtras 13.84ms
          ‒  lazyvim.plugins.extras.test.core 0.35ms
          ‒  lazyvim.plugins.extras.lang.typescript 0.53ms
          ‒  lazyvim.plugins.extras.formatting.prettier 0.13ms
          ‒  lazyvim.plugins.extras.coding.luasnip 0.46ms
          ‒  lazyvim.plugins.extras.coding.mini-comment 0.14ms
          ‒  lazyvim.plugins.extras.coding.mini-surround 0.1ms
          ‒  lazyvim.plugins.extras.coding.neogen 0.12ms
          ‒  lazyvim.plugins.extras.coding.yanky 0.08ms
          ‒  lazyvim.plugins.extras.dap.nlua 0.07ms
          ‒  lazyvim.plugins.extras.editor.dial 0.07ms
          ‒  lazyvim.plugins.extras.editor.harpoon2 0.19ms
          ‒  lazyvim.plugins.extras.editor.illuminate 0.19ms
          ‒  lazyvim.plugins.extras.editor.inc-rename 0.13ms
          ‒  lazyvim.plugins.extras.editor.leap 0.07ms
          ‒  lazyvim.plugins.extras.editor.mini-diff 0.14ms
          ‒  lazyvim.plugins.extras.editor.mini-files 0.07ms
          ‒  lazyvim.plugins.extras.editor.mini-move 0.06ms
          ‒  lazyvim.plugins.extras.editor.navic 0.06ms
          ‒  lazyvim.plugins.extras.editor.overseer 0.08ms
          ‒  lazyvim.plugins.extras.editor.refactoring 0.15ms
          ‒  lazyvim.plugins.extras.formatting.black 0.14ms
          ‒  lazyvim.plugins.extras.lang.ansible 0.14ms
          ‒  lazyvim.plugins.extras.lang.clangd 0.25ms
          ‒  lazyvim.plugins.extras.lang.cmake 0.15ms
          ‒  lazyvim.plugins.extras.lang.docker 0.09ms
          ‒  lazyvim.plugins.extras.lang.git 0.09ms
          ‒  lazyvim.plugins.extras.lang.go 0.14ms
          ‒  lazyvim.plugins.extras.lang.java 0.21ms
          ‒  lazyvim.plugins.extras.lang.json 0.08ms
          ‒  lazyvim.plugins.extras.lang.kotlin 0.1ms
          ‒  lazyvim.plugins.extras.lang.markdown 0.1ms
          ‒  lazyvim.plugins.extras.lang.php 0.23ms
          ‒  lazyvim.plugins.extras.lang.prisma 0.14ms
          ‒  lazyvim.plugins.extras.lang.python 0.32ms
          ‒  lazyvim.plugins.extras.lang.ruby 0.2ms
          ‒  lazyvim.plugins.extras.lang.rust 0.13ms
          ‒  lazyvim.plugins.extras.lang.scala 0.07ms
          ‒  lazyvim.plugins.extras.lang.sql 0.17ms
          ‒  lazyvim.plugins.extras.lang.svelte 0.08ms
          ‒  lazyvim.plugins.extras.lang.tailwind 0.08ms
          ‒  lazyvim.plugins.extras.lang.terraform 0.07ms
          ‒  lazyvim.plugins.extras.lang.toml 0.06ms
          ‒  lazyvim.plugins.extras.lang.vue 0.07ms
          ‒  lazyvim.plugins.extras.lang.yaml 0.06ms
          ‒  lazyvim.plugins.extras.linting.eslint 0.1ms
          ‒  lazyvim.plugins.extras.lsp.neoconf 0.09ms
          ‒  lazyvim.plugins.extras.ui.alpha 0.07ms
          ‒  lazyvim.plugins.extras.ui.mini-animate 0.19ms
          ‒  lazyvim.plugins.extras.ui.mini-indentscope 0.15ms
          ‒  lazyvim.plugins.extras.ui.mini-starter 0.06ms
          ‒  lazyvim.plugins.extras.ui.treesitter-context 0.06ms
          ‒  lazyvim.plugins.extras.util.chezmoi 0.08ms
          ‒  lazyvim.plugins.extras.util.dot 0.11ms
          ‒  lazyvim.plugins.extras.util.gitui 0.11ms
          ‒  lazyvim.plugins.extras.util.mini-hipatterns 0.13ms
          ‒  lazyvim.plugins.extras.util.octo 0.21ms
          ‒  lazyvim.plugins.extras.util.project 0.09ms
          ‒  lazyvim.plugins.extras.util.rest 1.03ms
          ‒  lazyvim.plugins.extras.util.startuptime 0.15ms
          ‒  lazyvim.plugins.extras.vscode 0.08ms
          ‒  lazyvim.plugins.extras.editor.aerial 0.15ms
          ‒  lazyvim.plugins.extras.editor.outline 0.08ms
        ★  plugins.example 0.27ms
        ★  resolve plugins 1.05ms
      ➜  state 1.03ms
      ➜  install 0.09ms
      ➜  handlers 9.53ms
        ★  nvim-ansible/ftdetect/ansible.lua 1.11ms
    ●  startup 13.21ms
      ➜  runtime/filetype.lua 0.34ms
      ➜  init 2.45ms
        ★  init  vim-dadbod-completion 0.01ms
        ★  init  lualine.nvim 0.01ms
        ★  init  fzf-lua 0ms
        ★  init  mason.nvim 0ms
        ★  init  mini.indentscope 0.02ms
        ★  init  chezmoi.nvim 0.01ms
        ★  init  chezmoi.vim 0ms
        ★  init  vim-dadbod-ui 0.01ms
        ★  init  nvim-navic 0ms
        ★  init  nvim-treesitter 2.02ms
        ★  init  nvim-notify 0.05ms
        ★  init  cmake-tools.nvim 0.07ms
        ★  init  mini.icons 0ms
        ★  init  conform.nvim 0ms
        ★  init  neo-tree.nvim 0.01ms
      ➜  start 6.3ms
        ★  start  LazyVim 6.21ms
          ‒  colorscheme 5.78ms
            ●  tokyonight.nvim 0.98ms
        ★  start  chezmoi.vim 0.05ms
      ➜  rtp plugins 4.03ms
        ★  runtime/plugin/editorconfig.lua 0.17ms
        ★  runtime/plugin/man.lua 0.15ms
        ★  runtime/plugin/matchit.vim 1.13ms
        ★  runtime/plugin/matchparen.vim 0.42ms
        ★  runtime/plugin/netrwPlugin.vim 0.56ms
        ★  runtime/plugin/osc52.lua 0.17ms
        ★  runtime/plugin/rplugin.vim 0.39ms
        ★  runtime/plugin/shada.vim 0.24ms
        ★  runtime/plugin/spellfile.vim 0.64ms
      ➜  after 0.05ms
    ●  startuptime 63.16ms
    ●  VeryLazy 85.64ms
      ➜  mini.comment 1.33ms
      ➜  lualine.nvim 26.12ms
        ★  trouble.nvim 4.16ms
      ➜  mini.diff 1.44ms
      ➜  nvim-treesitter-textobjects 9.7ms
        ★  nvim-treesitter-textobjects/plugin/nvim-treesitter-textobjects.vim 9.41ms
      ➜  mini.animate 5.65ms
        ★  which-key.nvim 2.35ms
          ‒  which-key.nvim/plugin/which-key.lua 0.34ms
      ➜  nvim-treesitter-context 3.08ms
        ★  nvim-treesitter-context/plugin/treesitter-context.lua 2.45ms
      ➜  nvim-treesitter 10.01ms
        ★  nvim-treesitter/plugin/nvim-treesitter.lua 0.62ms
      ➜  mini.pairs 3.02ms
      ➜  noice.nvim 3.11ms
      ➜  ts-comments.nvim 1.38ms
      ➜  mini.ai 1.51ms
      ➜  mini.move 1.27ms
      ➜  project.nvim 2.47ms
      ➜  vim-repeat 0.04ms
      ➜  bufferline.nvim 5.07ms
      ➜  treesitter_context_update 0.01ms
    ●  nui.nvim 0.09ms
    ●  nvim-notify 5.36ms
    ●  mini.icons 5.49ms
    ●  spec 20.36ms
      ➜  pkg 0.36ms
      ➜  lazyvim.plugins 0.19ms
      ➜  lazyvim.plugins.coding 0.23ms
      ➜  lazyvim.plugins.colorscheme 0.18ms
      ➜  lazyvim.plugins.editor 0.53ms
        ★  lazyvim.plugins.extras.editor.fzf 0.24ms
      ➜  lazyvim.plugins.formatting 0.18ms
      ➜  lazyvim.plugins.linting 0.26ms
      ➜  lazyvim.plugins.lsp 0.54ms
      ➜  lazyvim.plugins.treesitter 0.12ms
      ➜  lazyvim.plugins.ui 0.28ms
      ➜  lazyvim.plugins.util 0.17ms
      ➜  lazyvim.plugins.xtras 14.92ms
        ★  lazyvim.plugins.extras.test.core 0.22ms
        ★  lazyvim.plugins.extras.lang.typescript 0.42ms
        ★  lazyvim.plugins.extras.formatting.prettier 0.28ms
        ★  lazyvim.plugins.extras.coding.luasnip 0.25ms
        ★  lazyvim.plugins.extras.coding.mini-comment 1.13ms
        ★  lazyvim.plugins.extras.coding.mini-surround 0.13ms
        ★  lazyvim.plugins.extras.coding.neogen 0.09ms
        ★  lazyvim.plugins.extras.coding.yanky 0.12ms
        ★  lazyvim.plugins.extras.dap.nlua 0.1ms
        ★  lazyvim.plugins.extras.editor.dial 0.11ms
        ★  lazyvim.plugins.extras.editor.harpoon2 0.1ms
        ★  lazyvim.plugins.extras.editor.illuminate 0.11ms
        ★  lazyvim.plugins.extras.editor.inc-rename 0.11ms
        ★  lazyvim.plugins.extras.editor.leap 0.13ms
        ★  lazyvim.plugins.extras.editor.mini-diff 0.1ms
        ★  lazyvim.plugins.extras.editor.mini-files 0.12ms
        ★  lazyvim.plugins.extras.editor.mini-move 0.1ms
        ★  lazyvim.plugins.extras.editor.navic 0.11ms
        ★  lazyvim.plugins.extras.editor.overseer 0.13ms
        ★  lazyvim.plugins.extras.editor.refactoring 0.13ms
        ★  lazyvim.plugins.extras.formatting.black 0.1ms
        ★  lazyvim.plugins.extras.lang.ansible 0.16ms
        ★  lazyvim.plugins.extras.lang.clangd 0.2ms
        ★  lazyvim.plugins.extras.lang.cmake 0.27ms
        ★  lazyvim.plugins.extras.lang.docker 0.99ms
        ★  lazyvim.plugins.extras.lang.git 0.24ms
        ★  lazyvim.plugins.extras.lang.go 0.16ms
        ★  lazyvim.plugins.extras.lang.java 0.26ms
        ★  lazyvim.plugins.extras.lang.json 0.1ms
        ★  lazyvim.plugins.extras.lang.kotlin 0.35ms
        ★  lazyvim.plugins.extras.lang.markdown 0.47ms
        ★  lazyvim.plugins.extras.lang.php 0.24ms
        ★  lazyvim.plugins.extras.lang.prisma 0.22ms
        ★  lazyvim.plugins.extras.lang.python 0.59ms
        ★  lazyvim.plugins.extras.lang.ruby 0.29ms
        ★  lazyvim.plugins.extras.lang.rust 0.23ms
        ★  lazyvim.plugins.extras.lang.scala 0.14ms
        ★  lazyvim.plugins.extras.lang.sql 0.13ms
        ★  lazyvim.plugins.extras.lang.svelte 0.11ms
        ★  lazyvim.plugins.extras.lang.tailwind 0.22ms
        ★  lazyvim.plugins.extras.lang.terraform 0.17ms
        ★  lazyvim.plugins.extras.lang.toml 0.15ms
        ★  lazyvim.plugins.extras.lang.vue 0.15ms
        ★  lazyvim.plugins.extras.lang.yaml 0.12ms
        ★  lazyvim.plugins.extras.linting.eslint 0.09ms
        ★  lazyvim.plugins.extras.lsp.neoconf 0.09ms
        ★  lazyvim.plugins.extras.ui.alpha 0.1ms
        ★  lazyvim.plugins.extras.ui.mini-animate 0.09ms
        ★  lazyvim.plugins.extras.ui.mini-indentscope 0.09ms
        ★  lazyvim.plugins.extras.ui.mini-starter 0.1ms
        ★  lazyvim.plugins.extras.ui.treesitter-context 0.09ms
        ★  lazyvim.plugins.extras.util.chezmoi 0.13ms
        ★  lazyvim.plugins.extras.util.dot 0.11ms
        ★  lazyvim.plugins.extras.util.gitui 0.1ms
        ★  lazyvim.plugins.extras.util.mini-hipatterns 0.17ms
        ★  lazyvim.plugins.extras.util.octo 0.11ms
        ★  lazyvim.plugins.extras.util.project 0.12ms
        ★  lazyvim.plugins.extras.util.rest 0.14ms
        ★  lazyvim.plugins.extras.util.startuptime 0.09ms
        ★  lazyvim.plugins.extras.vscode 0.1ms
        ★  lazyvim.plugins.extras.editor.aerial 0.19ms
        ★  lazyvim.plugins.extras.editor.outline 0.1ms
      ➜  plugins.example 0.12ms
      ➜  resolve plugins 1.7ms
    ●  state 0.6ms
    ●  spec 20.13ms
      ➜  pkg 0.34ms
      ➜  lazyvim.plugins 0.19ms
      ➜  lazyvim.plugins.coding 0.34ms
      ➜  lazyvim.plugins.colorscheme 0.2ms
      ➜  lazyvim.plugins.editor 0.74ms
        ★  lazyvim.plugins.extras.editor.fzf 0.39ms
      ➜  lazyvim.plugins.formatting 0.28ms
      ➜  lazyvim.plugins.linting 0.27ms
      ➜  lazyvim.plugins.lsp 0.52ms
      ➜  lazyvim.plugins.treesitter 0.13ms
      ➜  lazyvim.plugins.ui 0.37ms
      ➜  lazyvim.plugins.util 0.16ms
      ➜  lazyvim.plugins.xtras 13.89ms
        ★  lazyvim.plugins.extras.test.core 0.32ms
        ★  lazyvim.plugins.extras.lang.typescript 0.28ms
        ★  lazyvim.plugins.extras.formatting.prettier 0.27ms
        ★  lazyvim.plugins.extras.coding.luasnip 0.29ms
        ★  lazyvim.plugins.extras.coding.mini-comment 0.25ms
        ★  lazyvim.plugins.extras.coding.mini-surround 1.17ms
        ★  lazyvim.plugins.extras.coding.neogen 0.12ms
        ★  lazyvim.plugins.extras.coding.yanky 0.09ms
        ★  lazyvim.plugins.extras.dap.nlua 0.09ms
        ★  lazyvim.plugins.extras.editor.dial 0.11ms
        ★  lazyvim.plugins.extras.editor.harpoon2 0.2ms
        ★  lazyvim.plugins.extras.editor.illuminate 0.09ms
        ★  lazyvim.plugins.extras.editor.inc-rename 0.09ms
        ★  lazyvim.plugins.extras.editor.leap 0.12ms
        ★  lazyvim.plugins.extras.editor.mini-diff 0.09ms
        ★  lazyvim.plugins.extras.editor.mini-files 0.09ms
        ★  lazyvim.plugins.extras.editor.mini-move 0.08ms
        ★  lazyvim.plugins.extras.editor.navic 0.09ms
        ★  lazyvim.plugins.extras.editor.overseer 0.1ms
        ★  lazyvim.plugins.extras.editor.refactoring 0.1ms
        ★  lazyvim.plugins.extras.formatting.black 0.09ms
        ★  lazyvim.plugins.extras.lang.ansible 0.14ms
        ★  lazyvim.plugins.extras.lang.clangd 0.28ms
        ★  lazyvim.plugins.extras.lang.cmake 0.19ms
        ★  lazyvim.plugins.extras.lang.docker 0.97ms
        ★  lazyvim.plugins.extras.lang.git 0.39ms
        ★  lazyvim.plugins.extras.lang.go 0.12ms
        ★  lazyvim.plugins.extras.lang.java 0.29ms
        ★  lazyvim.plugins.extras.lang.json 0.09ms
        ★  lazyvim.plugins.extras.lang.kotlin 0.22ms
        ★  lazyvim.plugins.extras.lang.markdown 0.19ms
        ★  lazyvim.plugins.extras.lang.php 0.28ms
        ★  lazyvim.plugins.extras.lang.prisma 0.21ms
        ★  lazyvim.plugins.extras.lang.python 0.72ms
        ★  lazyvim.plugins.extras.lang.ruby 0.22ms
        ★  lazyvim.plugins.extras.lang.rust 0.25ms
        ★  lazyvim.plugins.extras.lang.scala 0.1ms
        ★  lazyvim.plugins.extras.lang.sql 0.11ms
        ★  lazyvim.plugins.extras.lang.svelte 0.1ms
        ★  lazyvim.plugins.extras.lang.tailwind 0.2ms
        ★  lazyvim.plugins.extras.lang.terraform 0.22ms
        ★  lazyvim.plugins.extras.lang.toml 0.09ms
        ★  lazyvim.plugins.extras.lang.vue 0.09ms
        ★  lazyvim.plugins.extras.lang.yaml 0.09ms
        ★  lazyvim.plugins.extras.linting.eslint 0.09ms
        ★  lazyvim.plugins.extras.lsp.neoconf 0.09ms
        ★  lazyvim.plugins.extras.ui.alpha 0.1ms
        ★  lazyvim.plugins.extras.ui.mini-animate 0.09ms
        ★  lazyvim.plugins.extras.ui.mini-indentscope 0.09ms
        ★  lazyvim.plugins.extras.ui.mini-starter 0.2ms
        ★  lazyvim.plugins.extras.ui.treesitter-context 0.09ms
        ★  lazyvim.plugins.extras.util.chezmoi 0.12ms
        ★  lazyvim.plugins.extras.util.dot 0.1ms
        ★  lazyvim.plugins.extras.util.gitui 0.08ms
        ★  lazyvim.plugins.extras.util.mini-hipatterns 0.15ms
        ★  lazyvim.plugins.extras.util.octo 0.1ms
        ★  lazyvim.plugins.extras.util.project 0.1ms
        ★  lazyvim.plugins.extras.util.rest 0.11ms
        ★  lazyvim.plugins.extras.util.startuptime 0.14ms
        ★  lazyvim.plugins.extras.vscode 0.08ms
        ★  lazyvim.plugins.extras.editor.aerial 0.17ms
        ★  lazyvim.plugins.extras.editor.outline 0.08ms
      ➜  plugins.example 0.1ms
      ➜  resolve plugins 1.91ms
    ●  state 0.46ms
    ●  spec 24.22ms
      ➜  pkg 0.34ms
      ➜  lazyvim.plugins 0.36ms
      ➜  lazyvim.plugins.coding 0.39ms
      ➜  lazyvim.plugins.colorscheme 0.24ms
      ➜  lazyvim.plugins.editor 0.77ms
        ★  lazyvim.plugins.extras.editor.fzf 0.37ms
      ➜  lazyvim.plugins.formatting 0.24ms
      ➜  lazyvim.plugins.linting 0.22ms
      ➜  lazyvim.plugins.lsp 0.62ms
      ➜  lazyvim.plugins.treesitter 0.17ms
      ➜  lazyvim.plugins.ui 0.41ms
      ➜  lazyvim.plugins.util 0.2ms
      ➜  lazyvim.plugins.xtras 17.92ms
        ★  lazyvim.plugins.extras.test.core 0.24ms
        ★  lazyvim.plugins.extras.lang.typescript 0.29ms
        ★  lazyvim.plugins.extras.formatting.prettier 0.22ms
        ★  lazyvim.plugins.extras.coding.luasnip 0.25ms
        ★  lazyvim.plugins.extras.coding.mini-comment 1.15ms
        ★  lazyvim.plugins.extras.coding.mini-surround 0.11ms
        ★  lazyvim.plugins.extras.coding.neogen 0.1ms
        ★  lazyvim.plugins.extras.coding.yanky 0.11ms
        ★  lazyvim.plugins.extras.dap.nlua 0.1ms
        ★  lazyvim.plugins.extras.editor.dial 0.12ms
        ★  lazyvim.plugins.extras.editor.harpoon2 0.15ms
        ★  lazyvim.plugins.extras.editor.illuminate 0.1ms
        ★  lazyvim.plugins.extras.editor.inc-rename 0.1ms
        ★  lazyvim.plugins.extras.editor.leap 0.11ms
        ★  lazyvim.plugins.extras.editor.mini-diff 0.1ms
        ★  lazyvim.plugins.extras.editor.mini-files 0.11ms
        ★  lazyvim.plugins.extras.editor.mini-move 0.1ms
        ★  lazyvim.plugins.extras.editor.navic 0.11ms
        ★  lazyvim.plugins.extras.editor.overseer 0.22ms
        ★  lazyvim.plugins.extras.editor.refactoring 0.13ms
        ★  lazyvim.plugins.extras.formatting.black 0.1ms
        ★  lazyvim.plugins.extras.lang.ansible 0.1ms
        ★  lazyvim.plugins.extras.lang.clangd 0.21ms
        ★  lazyvim.plugins.extras.lang.cmake 0.21ms
        ★  lazyvim.plugins.extras.lang.docker 0.93ms
        ★  lazyvim.plugins.extras.lang.git 0.22ms
        ★  lazyvim.plugins.extras.lang.go 0.16ms
        ★  lazyvim.plugins.extras.lang.java 0.41ms
        ★  lazyvim.plugins.extras.lang.json 0.11ms
        ★  lazyvim.plugins.extras.lang.kotlin 0.73ms
        ★  lazyvim.plugins.extras.lang.markdown 0.27ms
        ★  lazyvim.plugins.extras.lang.php 0.21ms
        ★  lazyvim.plugins.extras.lang.prisma 0.22ms
        ★  lazyvim.plugins.extras.lang.python 1.23ms
        ★  lazyvim.plugins.extras.lang.ruby 0.73ms
        ★  lazyvim.plugins.extras.lang.rust 0.22ms
        ★  lazyvim.plugins.extras.lang.scala 0.12ms
        ★  lazyvim.plugins.extras.lang.sql 0.84ms
        ★  lazyvim.plugins.extras.lang.svelte 0.12ms
        ★  lazyvim.plugins.extras.lang.tailwind 0.39ms
        ★  lazyvim.plugins.extras.lang.terraform 0.41ms
        ★  lazyvim.plugins.extras.lang.toml 0.15ms
        ★  lazyvim.plugins.extras.lang.vue 0.1ms
        ★  lazyvim.plugins.extras.lang.yaml 0.1ms
        ★  lazyvim.plugins.extras.linting.eslint 0.1ms
        ★  lazyvim.plugins.extras.lsp.neoconf 0.27ms
        ★  lazyvim.plugins.extras.ui.alpha 0.11ms
        ★  lazyvim.plugins.extras.ui.mini-animate 0.1ms
        ★  lazyvim.plugins.extras.ui.mini-indentscope 0.1ms
        ★  lazyvim.plugins.extras.ui.mini-starter 0.11ms
        ★  lazyvim.plugins.extras.ui.treesitter-context 0.09ms
        ★  lazyvim.plugins.extras.util.chezmoi 0.14ms
        ★  lazyvim.plugins.extras.util.dot 0.16ms
        ★  lazyvim.plugins.extras.util.gitui 0.1ms
        ★  lazyvim.plugins.extras.util.mini-hipatterns 0.23ms
        ★  lazyvim.plugins.extras.util.octo 0.11ms
        ★  lazyvim.plugins.extras.util.project 0.6ms
        ★  lazyvim.plugins.extras.util.rest 0.11ms
        ★  lazyvim.plugins.extras.util.startuptime 0.16ms
        ★  lazyvim.plugins.extras.vscode 0.1ms
        ★  lazyvim.plugins.extras.editor.aerial 0.19ms
        ★  lazyvim.plugins.extras.editor.outline 0.1ms
      ➜  plugins.example 0.12ms
      ➜  resolve plugins 1.84ms
    ●  state 0.94ms
    ●  spec 23.07ms
      ➜  pkg 0.33ms
      ➜  lazyvim.plugins 0.37ms
      ➜  lazyvim.plugins.coding 1.4ms
      ➜  lazyvim.plugins.colorscheme 0.22ms
      ➜  lazyvim.plugins.editor 0.72ms
        ★  lazyvim.plugins.extras.editor.fzf 0.3ms
      ➜  lazyvim.plugins.formatting 0.18ms
      ➜  lazyvim.plugins.linting 0.22ms
      ➜  lazyvim.plugins.lsp 0.63ms
      ➜  lazyvim.plugins.treesitter 0.15ms
      ➜  lazyvim.plugins.ui 0.3ms
      ➜  lazyvim.plugins.util 0.17ms
      ➜  lazyvim.plugins.xtras 15.77ms
        ★  lazyvim.plugins.extras.test.core 0.22ms
        ★  lazyvim.plugins.extras.lang.typescript 0.29ms
        ★  lazyvim.plugins.extras.formatting.prettier 0.19ms
        ★  lazyvim.plugins.extras.coding.luasnip 0.34ms
        ★  lazyvim.plugins.extras.coding.mini-comment 1.07ms
        ★  lazyvim.plugins.extras.coding.mini-surround 0.11ms
        ★  lazyvim.plugins.extras.coding.neogen 0.09ms
        ★  lazyvim.plugins.extras.coding.yanky 0.09ms
        ★  lazyvim.plugins.extras.dap.nlua 0.09ms
        ★  lazyvim.plugins.extras.editor.dial 0.1ms
        ★  lazyvim.plugins.extras.editor.harpoon2 0.09ms
        ★  lazyvim.plugins.extras.editor.illuminate 0.28ms
        ★  lazyvim.plugins.extras.editor.inc-rename 0.33ms
        ★  lazyvim.plugins.extras.editor.leap 0.53ms
        ★  lazyvim.plugins.extras.editor.mini-diff 0.39ms
        ★  lazyvim.plugins.extras.editor.mini-files 0.13ms
        ★  lazyvim.plugins.extras.editor.mini-move 0.1ms
        ★  lazyvim.plugins.extras.editor.navic 0.1ms
        ★  lazyvim.plugins.extras.editor.overseer 0.1ms
        ★  lazyvim.plugins.extras.editor.refactoring 0.11ms
        ★  lazyvim.plugins.extras.formatting.black 0.14ms
        ★  lazyvim.plugins.extras.lang.ansible 0.09ms
        ★  lazyvim.plugins.extras.lang.clangd 0.19ms
        ★  lazyvim.plugins.extras.lang.cmake 0.19ms
        ★  lazyvim.plugins.extras.lang.docker 0.98ms
        ★  lazyvim.plugins.extras.lang.git 0.22ms
        ★  lazyvim.plugins.extras.lang.go 0.12ms
        ★  lazyvim.plugins.extras.lang.java 0.66ms
        ★  lazyvim.plugins.extras.lang.json 0.1ms
        ★  lazyvim.plugins.extras.lang.kotlin 0.66ms
        ★  lazyvim.plugins.extras.lang.markdown 0.29ms
        ★  lazyvim.plugins.extras.lang.php 0.2ms
        ★  lazyvim.plugins.extras.lang.prisma 0.21ms
        ★  lazyvim.plugins.extras.lang.python 1.17ms
        ★  lazyvim.plugins.extras.lang.ruby 0.69ms
        ★  lazyvim.plugins.extras.lang.rust 0.2ms
        ★  lazyvim.plugins.extras.lang.scala 0.12ms
        ★  lazyvim.plugins.extras.lang.sql 0.11ms
        ★  lazyvim.plugins.extras.lang.svelte 0.1ms
        ★  lazyvim.plugins.extras.lang.tailwind 0.2ms
        ★  lazyvim.plugins.extras.lang.terraform 0.16ms
        ★  lazyvim.plugins.extras.lang.toml 0.09ms
        ★  lazyvim.plugins.extras.lang.vue 0.09ms
        ★  lazyvim.plugins.extras.lang.yaml 0.09ms
        ★  lazyvim.plugins.extras.linting.eslint 0.08ms
        ★  lazyvim.plugins.extras.lsp.neoconf 0.09ms
        ★  lazyvim.plugins.extras.ui.alpha 0.09ms
        ★  lazyvim.plugins.extras.ui.mini-animate 0.09ms
        ★  lazyvim.plugins.extras.ui.mini-indentscope 0.09ms
        ★  lazyvim.plugins.extras.ui.mini-starter 0.09ms
        ★  lazyvim.plugins.extras.ui.treesitter-context 0.08ms
        ★  lazyvim.plugins.extras.util.chezmoi 0.12ms
        ★  lazyvim.plugins.extras.util.dot 0.09ms
        ★  lazyvim.plugins.extras.util.gitui 0.08ms
        ★  lazyvim.plugins.extras.util.mini-hipatterns 0.14ms
        ★  lazyvim.plugins.extras.util.octo 0.11ms
        ★  lazyvim.plugins.extras.util.project 0.1ms
        ★  lazyvim.plugins.extras.util.rest 0.09ms
        ★  lazyvim.plugins.extras.util.startuptime 0.08ms
        ★  lazyvim.plugins.extras.vscode 0.08ms
        ★  lazyvim.plugins.extras.editor.aerial 0.18ms
        ★  lazyvim.plugins.extras.editor.outline 0.09ms
      ➜  plugins.example 0.1ms
      ➜  resolve plugins 1.82ms
    ●  state 0.48ms
    ●  spec 12.7ms
      ➜  pkg 0.3ms
      ➜  lazyvim.plugins 0.09ms
      ➜  lazyvim.plugins.coding 0.16ms
      ➜  lazyvim.plugins.colorscheme 0.09ms
      ➜  lazyvim.plugins.editor 0.43ms
        ★  lazyvim.plugins.extras.editor.fzf 0.18ms
      ➜  lazyvim.plugins.formatting 0.09ms
      ➜  lazyvim.plugins.linting 0.08ms
      ➜  lazyvim.plugins.lsp 0.12ms
      ➜  lazyvim.plugins.treesitter 0.11ms
      ➜  lazyvim.plugins.ui 0.2ms
      ➜  lazyvim.plugins.util 0.08ms
      ➜  lazyvim.plugins.xtras 8.38ms
        ★  lazyvim.plugins.extras.test.core 0.12ms
        ★  lazyvim.plugins.extras.lang.typescript 0.14ms
        ★  lazyvim.plugins.extras.formatting.prettier 0.11ms
        ★  lazyvim.plugins.extras.coding.luasnip 0.12ms
        ★  lazyvim.plugins.extras.coding.mini-comment 0.08ms
        ★  lazyvim.plugins.extras.coding.mini-surround 0.07ms
        ★  lazyvim.plugins.extras.coding.neogen 0.08ms
        ★  lazyvim.plugins.extras.coding.yanky 0.09ms
        ★  lazyvim.plugins.extras.dap.nlua 0.09ms
        ★  lazyvim.plugins.extras.editor.dial 0.09ms
        ★  lazyvim.plugins.extras.editor.harpoon2 0.07ms
        ★  lazyvim.plugins.extras.editor.illuminate 0.08ms
        ★  lazyvim.plugins.extras.editor.inc-rename 0.08ms
        ★  lazyvim.plugins.extras.editor.leap 0.09ms
        ★  lazyvim.plugins.extras.editor.mini-diff 0.08ms
        ★  lazyvim.plugins.extras.editor.mini-files 0.14ms
        ★  lazyvim.plugins.extras.editor.mini-move 0.09ms
        ★  lazyvim.plugins.extras.editor.navic 0.12ms
        ★  lazyvim.plugins.extras.editor.overseer 0.14ms
        ★  lazyvim.plugins.extras.editor.refactoring 0.14ms
        ★  lazyvim.plugins.extras.formatting.black 0.08ms
        ★  lazyvim.plugins.extras.lang.ansible 0.08ms
        ★  lazyvim.plugins.extras.lang.clangd 0.11ms
        ★  lazyvim.plugins.extras.lang.cmake 0.09ms
        ★  lazyvim.plugins.extras.lang.docker 0.1ms
        ★  lazyvim.plugins.extras.lang.git 0.13ms
        ★  lazyvim.plugins.extras.lang.go 0.12ms
        ★  lazyvim.plugins.extras.lang.java 0.12ms
        ★  lazyvim.plugins.extras.lang.json 0.08ms
        ★  lazyvim.plugins.extras.lang.kotlin 0.1ms
        ★  lazyvim.plugins.extras.lang.markdown 0.11ms
        ★  lazyvim.plugins.extras.lang.php 0.09ms
        ★  lazyvim.plugins.extras.lang.prisma 0.07ms
        ★  lazyvim.plugins.extras.lang.python 0.12ms
        ★  lazyvim.plugins.extras.lang.ruby 0.28ms
        ★  lazyvim.plugins.extras.lang.rust 0.14ms
        ★  lazyvim.plugins.extras.lang.scala 0.09ms
        ★  lazyvim.plugins.extras.lang.sql 0.1ms
        ★  lazyvim.plugins.extras.lang.svelte 0.09ms
        ★  lazyvim.plugins.extras.lang.tailwind 0.08ms
        ★  lazyvim.plugins.extras.lang.terraform 0.1ms
        ★  lazyvim.plugins.extras.lang.toml 0.06ms
        ★  lazyvim.plugins.extras.lang.vue 0.08ms
        ★  lazyvim.plugins.extras.lang.yaml 0.09ms
        ★  lazyvim.plugins.extras.linting.eslint 0.08ms
        ★  lazyvim.plugins.extras.lsp.neoconf 0.08ms
        ★  lazyvim.plugins.extras.ui.alpha 0.09ms
        ★  lazyvim.plugins.extras.ui.mini-animate 0.08ms
        ★  lazyvim.plugins.extras.ui.mini-indentscope 0.08ms
        ★  lazyvim.plugins.extras.ui.mini-starter 0.09ms
        ★  lazyvim.plugins.extras.ui.treesitter-context 0.07ms
        ★  lazyvim.plugins.extras.util.chezmoi 0.12ms
        ★  lazyvim.plugins.extras.util.dot 0.08ms
        ★  lazyvim.plugins.extras.util.gitui 0.07ms
        ★  lazyvim.plugins.extras.util.mini-hipatterns 0.13ms
        ★  lazyvim.plugins.extras.util.octo 0.1ms
        ★  lazyvim.plugins.extras.util.project 0.1ms
        ★  lazyvim.plugins.extras.util.rest 0.07ms
        ★  lazyvim.plugins.extras.util.startuptime 0.07ms
        ★  lazyvim.plugins.extras.vscode 0.08ms
        ★  lazyvim.plugins.extras.editor.aerial 0.09ms
        ★  lazyvim.plugins.extras.editor.outline 0.08ms
      ➜  plugins.example 0.09ms
      ➜  resolve plugins 1.78ms
    ●  state 0.5ms
    ●  spec 17.88ms
      ➜  pkg 0.32ms
      ➜  lazyvim.plugins 0.08ms
      ➜  lazyvim.plugins.coding 0.46ms
      ➜  lazyvim.plugins.colorscheme 0.08ms
      ➜  lazyvim.plugins.editor 0.54ms
        ★  lazyvim.plugins.extras.editor.fzf 0.2ms
      ➜  lazyvim.plugins.formatting 0.15ms
      ➜  lazyvim.plugins.linting 0.07ms
      ➜  lazyvim.plugins.lsp 0.09ms
      ➜  lazyvim.plugins.treesitter 0.15ms
      ➜  lazyvim.plugins.ui 0.19ms
      ➜  lazyvim.plugins.util 0.07ms
      ➜  lazyvim.plugins.xtras 13.26ms
        ★  lazyvim.plugins.extras.test.core 0.09ms
        ★  lazyvim.plugins.extras.lang.typescript 0.12ms
        ★  lazyvim.plugins.extras.formatting.prettier 0.14ms
        ★  lazyvim.plugins.extras.coding.luasnip 0.09ms
        ★  lazyvim.plugins.extras.coding.mini-comment 0.07ms
        ★  lazyvim.plugins.extras.coding.mini-surround 0.07ms
        ★  lazyvim.plugins.extras.coding.neogen 0.07ms
        ★  lazyvim.plugins.extras.coding.yanky 0.11ms
        ★  lazyvim.plugins.extras.dap.nlua 0.08ms
        ★  lazyvim.plugins.extras.editor.dial 0.08ms
        ★  lazyvim.plugins.extras.editor.harpoon2 0.07ms
        ★  lazyvim.plugins.extras.editor.illuminate 0.07ms
        ★  lazyvim.plugins.extras.editor.inc-rename 0.1ms
        ★  lazyvim.plugins.extras.editor.leap 0.25ms
        ★  lazyvim.plugins.extras.editor.mini-diff 0.09ms
        ★  lazyvim.plugins.extras.editor.mini-files 0.08ms
        ★  lazyvim.plugins.extras.editor.mini-move 0.06ms
        ★  lazyvim.plugins.extras.editor.navic 0.1ms
        ★  lazyvim.plugins.extras.editor.overseer 0.13ms
        ★  lazyvim.plugins.extras.editor.refactoring 0.08ms
        ★  lazyvim.plugins.extras.formatting.black 0.12ms
        ★  lazyvim.plugins.extras.lang.ansible 0.34ms
        ★  lazyvim.plugins.extras.lang.clangd 0.61ms
        ★  lazyvim.plugins.extras.lang.cmake 0.55ms
        ★  lazyvim.plugins.extras.lang.docker 0.14ms
        ★  lazyvim.plugins.extras.lang.git 0.08ms
        ★  lazyvim.plugins.extras.lang.go 0.09ms
        ★  lazyvim.plugins.extras.lang.java 0.11ms
        ★  lazyvim.plugins.extras.lang.json 0.06ms
        ★  lazyvim.plugins.extras.lang.kotlin 0.54ms
        ★  lazyvim.plugins.extras.lang.markdown 0.09ms
        ★  lazyvim.plugins.extras.lang.php 0.08ms
        ★  lazyvim.plugins.extras.lang.prisma 0.06ms
        ★  lazyvim.plugins.extras.lang.python 0.7ms
        ★  lazyvim.plugins.extras.lang.ruby 0.5ms
        ★  lazyvim.plugins.extras.lang.rust 0.63ms
        ★  lazyvim.plugins.extras.lang.scala 0.07ms
        ★  lazyvim.plugins.extras.lang.sql 0.63ms
        ★  lazyvim.plugins.extras.lang.svelte 0.07ms
        ★  lazyvim.plugins.extras.lang.tailwind 0.3ms
        ★  lazyvim.plugins.extras.lang.terraform 0.36ms
        ★  lazyvim.plugins.extras.lang.toml 0.06ms
        ★  lazyvim.plugins.extras.lang.vue 0.12ms
        ★  lazyvim.plugins.extras.lang.yaml 0.07ms
        ★  lazyvim.plugins.extras.linting.eslint 0.06ms
        ★  lazyvim.plugins.extras.lsp.neoconf 0.23ms
        ★  lazyvim.plugins.extras.ui.alpha 0.07ms
        ★  lazyvim.plugins.extras.ui.mini-animate 0.06ms
        ★  lazyvim.plugins.extras.ui.mini-indentscope 0.06ms
        ★  lazyvim.plugins.extras.ui.mini-starter 0.12ms
        ★  lazyvim.plugins.extras.ui.treesitter-context 0.06ms
        ★  lazyvim.plugins.extras.util.chezmoi 0.09ms
        ★  lazyvim.plugins.extras.util.dot 0.07ms
        ★  lazyvim.plugins.extras.util.gitui 0.06ms
        ★  lazyvim.plugins.extras.util.mini-hipatterns 0.17ms
        ★  lazyvim.plugins.extras.util.octo 0.07ms
        ★  lazyvim.plugins.extras.util.project 0.53ms
        ★  lazyvim.plugins.extras.util.rest 0.07ms
        ★  lazyvim.plugins.extras.util.startuptime 0.13ms
        ★  lazyvim.plugins.extras.vscode 0.06ms
        ★  lazyvim.plugins.extras.editor.aerial 0.07ms
        ★  lazyvim.plugins.extras.editor.outline 0.06ms
      ➜  plugins.example 0.13ms
      ➜  resolve plugins 1.68ms
    ●  state 1.04ms
    ●  spec 10.33ms
      ➜  pkg 0.2ms
      ➜  lazyvim.plugins 0.08ms
      ➜  lazyvim.plugins.coding 0.66ms
      ➜  lazyvim.plugins.colorscheme 0.07ms
      ➜  lazyvim.plugins.editor 0.32ms
        ★  lazyvim.plugins.extras.editor.fzf 0.15ms
      ➜  lazyvim.plugins.formatting 0.06ms
      ➜  lazyvim.plugins.linting 0.04ms
      ➜  lazyvim.plugins.lsp 0.07ms
      ➜  lazyvim.plugins.treesitter 0.06ms
      ➜  lazyvim.plugins.ui 0.1ms
      ➜  lazyvim.plugins.util 0.04ms
      ➜  lazyvim.plugins.xtras 6.23ms
        ★  lazyvim.plugins.extras.test.core 0.12ms
        ★  lazyvim.plugins.extras.lang.typescript 0.09ms
        ★  lazyvim.plugins.extras.formatting.prettier 0.06ms
        ★  lazyvim.plugins.extras.coding.luasnip 0.09ms
        ★  lazyvim.plugins.extras.coding.mini-comment 0.04ms
        ★  lazyvim.plugins.extras.coding.mini-surround 0.06ms
        ★  lazyvim.plugins.extras.coding.neogen 0.04ms
        ★  lazyvim.plugins.extras.coding.yanky 0.09ms
        ★  lazyvim.plugins.extras.dap.nlua 0.04ms
        ★  lazyvim.plugins.extras.editor.dial 0.05ms
        ★  lazyvim.plugins.extras.editor.harpoon2 0.04ms
        ★  lazyvim.plugins.extras.editor.illuminate 0.04ms
        ★  lazyvim.plugins.extras.editor.inc-rename 0.04ms
        ★  lazyvim.plugins.extras.editor.leap 0.09ms
        ★  lazyvim.plugins.extras.editor.mini-diff 0.04ms
        ★  lazyvim.plugins.extras.editor.mini-files 0.05ms
        ★  lazyvim.plugins.extras.editor.mini-move 0.04ms
        ★  lazyvim.plugins.extras.editor.navic 0.04ms
        ★  lazyvim.plugins.extras.editor.overseer 0.05ms
        ★  lazyvim.plugins.extras.editor.refactoring 0.08ms
        ★  lazyvim.plugins.extras.formatting.black 0.04ms
        ★  lazyvim.plugins.extras.lang.ansible 0.04ms
        ★  lazyvim.plugins.extras.lang.clangd 0.32ms
        ★  lazyvim.plugins.extras.lang.cmake 0.29ms
        ★  lazyvim.plugins.extras.lang.docker 0.34ms
        ★  lazyvim.plugins.extras.lang.git 0.25ms
        ★  lazyvim.plugins.extras.lang.go 0.07ms
        ★  lazyvim.plugins.extras.lang.java 0.06ms
        ★  lazyvim.plugins.extras.lang.json 0.04ms
        ★  lazyvim.plugins.extras.lang.kotlin 0.06ms
        ★  lazyvim.plugins.extras.lang.markdown 0.08ms
        ★  lazyvim.plugins.extras.lang.php 0.05ms
        ★  lazyvim.plugins.extras.lang.prisma 0.04ms
        ★  lazyvim.plugins.extras.lang.python 0.06ms
        ★  lazyvim.plugins.extras.lang.ruby 0.05ms
        ★  lazyvim.plugins.extras.lang.rust 0.06ms
        ★  lazyvim.plugins.extras.lang.scala 0.05ms
        ★  lazyvim.plugins.extras.lang.sql 0.13ms
        ★  lazyvim.plugins.extras.lang.svelte 0.06ms
        ★  lazyvim.plugins.extras.lang.tailwind 0.05ms
        ★  lazyvim.plugins.extras.lang.terraform 0.06ms
        ★  lazyvim.plugins.extras.lang.toml 0.04ms
        ★  lazyvim.plugins.extras.lang.vue 0.06ms
        ★  lazyvim.plugins.extras.lang.yaml 0.06ms
        ★  lazyvim.plugins.extras.linting.eslint 0.04ms
        ★  lazyvim.plugins.extras.lsp.neoconf 0.04ms
        ★  lazyvim.plugins.extras.ui.alpha 0.07ms
        ★  lazyvim.plugins.extras.ui.mini-animate 0.04ms
        ★  lazyvim.plugins.extras.ui.mini-indentscope 0.04ms
        ★  lazyvim.plugins.extras.ui.mini-starter 0.04ms
        ★  lazyvim.plugins.extras.ui.treesitter-context 0.04ms
        ★  lazyvim.plugins.extras.util.chezmoi 0.09ms
        ★  lazyvim.plugins.extras.util.dot 0.04ms
        ★  lazyvim.plugins.extras.util.gitui 0.04ms
        ★  lazyvim.plugins.extras.util.mini-hipatterns 0.07ms
        ★  lazyvim.plugins.extras.util.octo 0.07ms
        ★  lazyvim.plugins.extras.util.project 0.05ms
        ★  lazyvim.plugins.extras.util.rest 0.06ms
        ★  lazyvim.plugins.extras.util.startuptime 0.04ms
        ★  lazyvim.plugins.extras.vscode 0.04ms
        ★  lazyvim.plugins.extras.editor.aerial 0.05ms
        ★  lazyvim.plugins.extras.editor.outline 0.04ms
      ➜  plugins.example 0.05ms
      ➜  resolve plugins 1.8ms
    ●  state 0.73ms
    ●  spec 24.88ms
      ➜  pkg 0.29ms
      ➜  lazyvim.plugins 0.29ms
      ➜  lazyvim.plugins.coding 0.32ms
      ➜  lazyvim.plugins.colorscheme 0.2ms
      ➜  lazyvim.plugins.editor 0.71ms
        ★  lazyvim.plugins.extras.editor.fzf 0.38ms
      ➜  lazyvim.plugins.formatting 0.24ms
      ➜  lazyvim.plugins.linting 0.24ms
      ➜  lazyvim.plugins.lsp 0.63ms
      ➜  lazyvim.plugins.treesitter 0.14ms
      ➜  lazyvim.plugins.ui 0.38ms
      ➜  lazyvim.plugins.util 0.14ms
      ➜  lazyvim.plugins.xtras 19.12ms
        ★  lazyvim.plugins.extras.test.core 0.29ms
        ★  lazyvim.plugins.extras.lang.typescript 0.2ms
        ★  lazyvim.plugins.extras.formatting.prettier 0.25ms
        ★  lazyvim.plugins.extras.coding.luasnip 0.33ms
        ★  lazyvim.plugins.extras.coding.mini-comment 0.19ms
        ★  lazyvim.plugins.extras.coding.mini-surround 1.14ms
        ★  lazyvim.plugins.extras.coding.neogen 0.2ms
        ★  lazyvim.plugins.extras.coding.yanky 0.19ms
        ★  lazyvim.plugins.extras.dap.nlua 0.07ms
        ★  lazyvim.plugins.extras.editor.dial 0.08ms
        ★  lazyvim.plugins.extras.editor.harpoon2 0.24ms
        ★  lazyvim.plugins.extras.editor.illuminate 0.07ms
        ★  lazyvim.plugins.extras.editor.inc-rename 0.34ms
        ★  lazyvim.plugins.extras.editor.leap 0.1ms
        ★  lazyvim.plugins.extras.editor.mini-diff 0.07ms
        ★  lazyvim.plugins.extras.editor.mini-files 0.07ms
        ★  lazyvim.plugins.extras.editor.mini-move 0.08ms
        ★  lazyvim.plugins.extras.editor.navic 0.13ms
        ★  lazyvim.plugins.extras.editor.overseer 0.14ms
        ★  lazyvim.plugins.extras.editor.refactoring 0.11ms
        ★  lazyvim.plugins.extras.formatting.black 0.06ms
        ★  lazyvim.plugins.extras.lang.ansible 0.06ms
        ★  lazyvim.plugins.extras.lang.clangd 0.27ms
        ★  lazyvim.plugins.extras.lang.cmake 0.18ms
        ★  lazyvim.plugins.extras.lang.docker 0.96ms
        ★  lazyvim.plugins.extras.lang.git 0.48ms
        ★  lazyvim.plugins.extras.lang.go 0.94ms
        ★  lazyvim.plugins.extras.lang.java 0.64ms
        ★  lazyvim.plugins.extras.lang.json 0.13ms
        ★  lazyvim.plugins.extras.lang.kotlin 0.19ms
        ★  lazyvim.plugins.extras.lang.markdown 0.24ms
        ★  lazyvim.plugins.extras.lang.php 0.34ms
        ★  lazyvim.plugins.extras.lang.prisma 0.21ms
        ★  lazyvim.plugins.extras.lang.python 1.15ms
        ★  lazyvim.plugins.extras.lang.ruby 0.75ms
        ★  lazyvim.plugins.extras.lang.rust 0.66ms
        ★  lazyvim.plugins.extras.lang.scala 0.3ms
        ★  lazyvim.plugins.extras.lang.sql 0.75ms
        ★  lazyvim.plugins.extras.lang.svelte 0.11ms
        ★  lazyvim.plugins.extras.lang.tailwind 0.25ms
        ★  lazyvim.plugins.extras.lang.terraform 0.13ms
        ★  lazyvim.plugins.extras.lang.toml 0.16ms
        ★  lazyvim.plugins.extras.lang.vue 0.13ms
        ★  lazyvim.plugins.extras.lang.yaml 0.27ms
        ★  lazyvim.plugins.extras.linting.eslint 0.09ms
        ★  lazyvim.plugins.extras.lsp.neoconf 0.09ms
        ★  lazyvim.plugins.extras.ui.alpha 0.2ms
        ★  lazyvim.plugins.extras.ui.mini-animate 0.08ms
        ★  lazyvim.plugins.extras.ui.mini-indentscope 0.08ms
        ★  lazyvim.plugins.extras.ui.mini-starter 0.26ms
        ★  lazyvim.plugins.extras.ui.treesitter-context 0.07ms
        ★  lazyvim.plugins.extras.util.chezmoi 0.14ms
        ★  lazyvim.plugins.extras.util.dot 0.08ms
        ★  lazyvim.plugins.extras.util.gitui 0.07ms
        ★  lazyvim.plugins.extras.util.mini-hipatterns 0.23ms
        ★  lazyvim.plugins.extras.util.octo 0.12ms
        ★  lazyvim.plugins.extras.util.project 0.12ms
        ★  lazyvim.plugins.extras.util.rest 0.1ms
        ★  lazyvim.plugins.extras.util.startuptime 0.07ms
        ★  lazyvim.plugins.extras.vscode 0.09ms
        ★  lazyvim.plugins.extras.editor.aerial 0.17ms
        ★  lazyvim.plugins.extras.editor.outline 0.14ms
      ➜  plugins.example 0.1ms
      ➜  resolve plugins 1.54ms
    ●  state 0.62ms
    ●  spec 18.72ms
      ➜  pkg 0.32ms
      ➜  lazyvim.plugins 0.3ms
      ➜  lazyvim.plugins.coding 0.98ms
      ➜  lazyvim.plugins.colorscheme 0.19ms
      ➜  lazyvim.plugins.editor 0.69ms
        ★  lazyvim.plugins.extras.editor.fzf 0.35ms
      ➜  lazyvim.plugins.formatting 0.28ms
      ➜  lazyvim.plugins.linting 0.2ms
      ➜  lazyvim.plugins.lsp 0.56ms
      ➜  lazyvim.plugins.treesitter 0.09ms
      ➜  lazyvim.plugins.ui 0.25ms
      ➜  lazyvim.plugins.util 0.15ms
      ➜  lazyvim.plugins.xtras 12.81ms
        ★  lazyvim.plugins.extras.test.core 0.29ms
        ★  lazyvim.plugins.extras.lang.typescript 0.21ms
        ★  lazyvim.plugins.extras.formatting.prettier 0.24ms
        ★  lazyvim.plugins.extras.coding.luasnip 0.47ms
        ★  lazyvim.plugins.extras.coding.mini-comment 0.21ms
        ★  lazyvim.plugins.extras.coding.mini-surround 1.14ms
        ★  lazyvim.plugins.extras.coding.neogen 0.07ms
        ★  lazyvim.plugins.extras.coding.yanky 0.08ms
        ★  lazyvim.plugins.extras.dap.nlua 0.07ms
        ★  lazyvim.plugins.extras.editor.dial 0.08ms
        ★  lazyvim.plugins.extras.editor.harpoon2 0.18ms
        ★  lazyvim.plugins.extras.editor.illuminate 0.07ms
        ★  lazyvim.plugins.extras.editor.inc-rename 0.07ms
        ★  lazyvim.plugins.extras.editor.leap 0.07ms
        ★  lazyvim.plugins.extras.editor.mini-diff 0.07ms
        ★  lazyvim.plugins.extras.editor.mini-files 0.07ms
        ★  lazyvim.plugins.extras.editor.mini-move 0.06ms
        ★  lazyvim.plugins.extras.editor.navic 0.07ms
        ★  lazyvim.plugins.extras.editor.overseer 0.59ms
        ★  lazyvim.plugins.extras.editor.refactoring 0.11ms
        ★  lazyvim.plugins.extras.formatting.black 0.07ms
        ★  lazyvim.plugins.extras.lang.ansible 0.07ms
        ★  lazyvim.plugins.extras.lang.clangd 0.52ms
        ★  lazyvim.plugins.extras.lang.cmake 0.22ms
        ★  lazyvim.plugins.extras.lang.docker 0.95ms
        ★  lazyvim.plugins.extras.lang.git 0.29ms
        ★  lazyvim.plugins.extras.lang.go 0.1ms
        ★  lazyvim.plugins.extras.lang.java 0.21ms
        ★  lazyvim.plugins.extras.lang.json 0.07ms
        ★  lazyvim.plugins.extras.lang.kotlin 0.17ms
        ★  lazyvim.plugins.extras.lang.markdown 0.19ms
        ★  lazyvim.plugins.extras.lang.php 0.25ms
        ★  lazyvim.plugins.extras.lang.prisma 0.2ms
        ★  lazyvim.plugins.extras.lang.python 0.74ms
        ★  lazyvim.plugins.extras.lang.ruby 0.21ms
        ★  lazyvim.plugins.extras.lang.rust 0.24ms
        ★  lazyvim.plugins.extras.lang.scala 0.07ms
        ★  lazyvim.plugins.extras.lang.sql 0.08ms
        ★  lazyvim.plugins.extras.lang.svelte 0.07ms
        ★  lazyvim.plugins.extras.lang.tailwind 0.14ms
        ★  lazyvim.plugins.extras.lang.terraform 0.08ms
        ★  lazyvim.plugins.extras.lang.toml 0.06ms
        ★  lazyvim.plugins.extras.lang.vue 0.08ms
        ★  lazyvim.plugins.extras.lang.yaml 0.08ms
        ★  lazyvim.plugins.extras.linting.eslint 0.06ms
        ★  lazyvim.plugins.extras.lsp.neoconf 0.06ms
        ★  lazyvim.plugins.extras.ui.alpha 0.09ms
        ★  lazyvim.plugins.extras.ui.mini-animate 0.06ms
        ★  lazyvim.plugins.extras.ui.mini-indentscope 0.06ms
        ★  lazyvim.plugins.extras.ui.mini-starter 0.16ms
        ★  lazyvim.plugins.extras.ui.treesitter-context 0.06ms
        ★  lazyvim.plugins.extras.util.chezmoi 0.12ms
        ★  lazyvim.plugins.extras.util.dot 0.07ms
        ★  lazyvim.plugins.extras.util.gitui 0.06ms
        ★  lazyvim.plugins.extras.util.mini-hipatterns 0.1ms
        ★  lazyvim.plugins.extras.util.octo 0.09ms
        ★  lazyvim.plugins.extras.util.project 0.07ms
        ★  lazyvim.plugins.extras.util.rest 0.08ms
        ★  lazyvim.plugins.extras.util.startuptime 0.06ms
        ★  lazyvim.plugins.extras.vscode 0.06ms
        ★  lazyvim.plugins.extras.editor.aerial 0.15ms
        ★  lazyvim.plugins.extras.editor.outline 0.07ms
      ➜  plugins.example 0.07ms
      ➜  resolve plugins 1.5ms
    ●  state 0.7ms
    ●  spec 15.62ms
      ➜  pkg 0.35ms
      ➜  lazyvim.plugins 0.22ms
      ➜  lazyvim.plugins.coding 0.22ms
      ➜  lazyvim.plugins.colorscheme 0.13ms
      ➜  lazyvim.plugins.editor 0.48ms
        ★  lazyvim.plugins.extras.editor.fzf 0.21ms
      ➜  lazyvim.plugins.formatting 0.15ms
      ➜  lazyvim.plugins.linting 0.19ms
      ➜  lazyvim.plugins.lsp 0.59ms
      ➜  lazyvim.plugins.treesitter 0.1ms
      ➜  lazyvim.plugins.ui 0.23ms
      ➜  lazyvim.plugins.util 0.15ms
      ➜  lazyvim.plugins.xtras 10.64ms
        ★  lazyvim.plugins.extras.test.core 0.22ms
        ★  lazyvim.plugins.extras.lang.typescript 0.2ms
        ★  lazyvim.plugins.extras.formatting.prettier 0.16ms
        ★  lazyvim.plugins.extras.coding.luasnip 0.23ms
        ★  lazyvim.plugins.extras.coding.mini-comment 1.13ms
        ★  lazyvim.plugins.extras.coding.mini-surround 0.1ms
        ★  lazyvim.plugins.extras.coding.neogen 0.07ms
        ★  lazyvim.plugins.extras.coding.yanky 0.07ms
        ★  lazyvim.plugins.extras.dap.nlua 0.07ms
        ★  lazyvim.plugins.extras.editor.dial 0.07ms
        ★  lazyvim.plugins.extras.editor.harpoon2 0.07ms
        ★  lazyvim.plugins.extras.editor.illuminate 0.07ms
        ★  lazyvim.plugins.extras.editor.inc-rename 0.07ms
        ★  lazyvim.plugins.extras.editor.leap 0.07ms
        ★  lazyvim.plugins.extras.editor.mini-diff 0.07ms
        ★  lazyvim.plugins.extras.editor.mini-files 0.07ms
        ★  lazyvim.plugins.extras.editor.mini-move 0.06ms
        ★  lazyvim.plugins.extras.editor.navic 0.07ms
        ★  lazyvim.plugins.extras.editor.overseer 0.08ms
        ★  lazyvim.plugins.extras.editor.refactoring 0.1ms
        ★  lazyvim.plugins.extras.formatting.black 0.06ms
        ★  lazyvim.plugins.extras.lang.ansible 0.07ms
        ★  lazyvim.plugins.extras.lang.clangd 0.16ms
        ★  lazyvim.plugins.extras.lang.cmake 0.17ms
        ★  lazyvim.plugins.extras.lang.docker 1ms
        ★  lazyvim.plugins.extras.lang.git 0.22ms
        ★  lazyvim.plugins.extras.lang.go 0.1ms
        ★  lazyvim.plugins.extras.lang.java 0.2ms
        ★  lazyvim.plugins.extras.lang.json 0.06ms
        ★  lazyvim.plugins.extras.lang.kotlin 0.17ms
        ★  lazyvim.plugins.extras.lang.markdown 0.18ms
        ★  lazyvim.plugins.extras.lang.php 0.16ms
        ★  lazyvim.plugins.extras.lang.prisma 0.18ms
        ★  lazyvim.plugins.extras.lang.python 0.54ms
        ★  lazyvim.plugins.extras.lang.ruby 0.19ms
        ★  lazyvim.plugins.extras.lang.rust 0.28ms
        ★  lazyvim.plugins.extras.lang.scala 0.07ms
        ★  lazyvim.plugins.extras.lang.sql 0.08ms
        ★  lazyvim.plugins.extras.lang.svelte 0.07ms
        ★  lazyvim.plugins.extras.lang.tailwind 0.14ms
        ★  lazyvim.plugins.extras.lang.terraform 0.08ms
        ★  lazyvim.plugins.extras.lang.toml 0.06ms
        ★  lazyvim.plugins.extras.lang.vue 0.08ms
        ★  lazyvim.plugins.extras.lang.yaml 0.08ms
        ★  lazyvim.plugins.extras.linting.eslint 0.06ms
        ★  lazyvim.plugins.extras.lsp.neoconf 0.06ms
        ★  lazyvim.plugins.extras.ui.alpha 0.09ms
        ★  lazyvim.plugins.extras.ui.mini-animate 0.06ms
        ★  lazyvim.plugins.extras.ui.mini-indentscope 0.06ms
        ★  lazyvim.plugins.extras.ui.mini-starter 0.07ms
        ★  lazyvim.plugins.extras.ui.treesitter-context 0.06ms
        ★  lazyvim.plugins.extras.util.chezmoi 0.11ms
        ★  lazyvim.plugins.extras.util.dot 0.06ms
        ★  lazyvim.plugins.extras.util.gitui 0.07ms
        ★  lazyvim.plugins.extras.util.mini-hipatterns 0.1ms
        ★  lazyvim.plugins.extras.util.octo 0.09ms
        ★  lazyvim.plugins.extras.util.project 0.07ms
        ★  lazyvim.plugins.extras.util.rest 0.08ms
        ★  lazyvim.plugins.extras.util.startuptime 0.06ms
        ★  lazyvim.plugins.extras.vscode 0.06ms
        ★  lazyvim.plugins.extras.editor.aerial 0.15ms
        ★  lazyvim.plugins.extras.editor.outline 0.06ms
      ➜  plugins.example 0.1ms
      ➜  resolve plugins 1.51ms
    ●  state 0.51ms
    ●  y 55.76ms
      ➜  yanky.nvim 55.62ms
        ★  yanky.nvim/plugin/init.lua 12.52ms
